Add build_binaries job to pipeline
We've added gppkg as an input for jobs that aren't yet using it. This is
only to maintain the structure & triggering pattern of the gpbackup
pipeline.

Co-authored-by: Kevin Yeap <kyeap@pivotal.io>
Co-authored-by: Larry Hamel <lhamel@pivotal.io>
Co-authored-by: Trevor Yacovone <tyacovone@pivotal.io>
Co-authored-by: Junkeun Yi <juyi@pivotal.io>

diff --git a/ci/pipeline.yml b/ci/pipeline.yml
--- a/ci/pipeline.yml
+++ b/ci/pipeline.yml
@@ -2,6 +2,7 @@
 groups:
 - name: All
   jobs:
+  - build_binaries
   - GPDB4.3
   - GPDB5
   - GPDB5-oracle7
@@ -99,6 +100,7 @@ resources:
     start: 6:00 AM
     stop: 7:00 AM
 
+# TODO mark these as src with name change
 - name: gpbackup
   type: git
   source:
@@ -117,6 +119,13 @@ resources:
     branch: master
     private_key: {{gpbackup-ddboost-plugin-remote-key}}
     uri: {{gpbackup-ddboost-plugin-git-remote}}
+
+- name: gpbackup_manager_src
+  type: git
+  source:
+    branch: master
+    private_key: {{gp-backup-manager-remote-deploy-key}}
+    uri: {{gp-backup-manager-git-remote}}
 
 - name: gpbackup_tagged_src
   type: git
@@ -372,6 +381,195 @@ resources:
     regexp: gpbackup-osl-v(.*).txt
 
 jobs:
+- name: build_binaries
+  plan:
+  - aggregate:
+    - get: gpbackup
+      trigger: true
+    - get: gpdb6_src
+    - get: bin_gpdb_6x_stable_centos6
+    - get: gpbackup_s3_plugin
+    - get: gpbackup-dependencies
+    - get: gpbackup_manager_src
+    - get: gpbackup_ddboost_plugin_tagged_src
+    - get: nightly-trigger
+      trigger: true
+  - aggregate:
+    - task: build-go-binaries
+      config:
+        platform: linux
+        inputs:
+          - name: gpbackup-dependencies
+          - name: gpbackup
+            path: go/src/github.com/greenplum-db/gpbackup
+          - name: gpbackup_s3_plugin
+            path: go/src/github.com/greenplum-db/gpbackup-s3-plugin
+          - name: gpbackup_manager_src
+            path: go/src/github.com/pivotal/gp-backup-manager
+        outputs:
+          - name: go_components
+        image_resource:
+          type: docker-image
+          source:
+            repository: golang
+            tag: '1.12.5'
+        run:
+          path: bash
+          args:
+          - -c
+          - |
+            set -ex
+            export GOPATH=$(pwd)/go
+            export PATH=$PATH:$GOPATH/bin
+
+            tar -zxf gpbackup-dependencies/dependencies.tar.gz -C $GOPATH/src/github.com/greenplum-db/gpbackup/
+
+            # Build gpbackup
+            pushd $GOPATH/src/github.com/greenplum-db/gpbackup
+              make depend
+
+              # NOTE: we are building binaries without a cluster installed, so distributing the backup_helper fails--continue anyway
+              make build || true
+              version=`git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/'`
+            popd
+            echo ${version} > go_components/gpbackup_version
+
+            # Build s3 plugin
+            pushd $GOPATH/src/github.com/greenplum-db/gpbackup-s3-plugin
+              make depend
+              make build
+              s3_plugin_version=`git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/'`
+            popd
+            echo ${s3_plugin_version} > go_components/s3_plugin_version
+
+            # gpbackup-manager
+            pushd $GOPATH/src/github.com/pivotal/gp-backup-manager
+              make depend
+              make build
+              gpbackup_manager_version=`git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/'`
+            popd
+            echo ${gpbackup_manager_version} > go_components/gpbackup_manager_version
+
+            cp $GOPATH/bin/gpbackup go_components/
+            cp $GOPATH/bin/gpbackup_helper go_components/
+            cp $GOPATH/bin/gprestore go_components/
+            cp $GOPATH/bin/gpbackup_s3_plugin go_components/
+            cp $GOPATH/bin/gpbackup_manager go_components/
+    - task: build-ddboost
+      params:
+        IVYREPO_USER: {{ivyrepo_user}}
+        IVYREPO_PASSWD: {{ivyrepo_passwd}}
+        IVYREPO_HOST: {{ivyrepo_host}}
+      config:
+        platform: linux
+        inputs:
+          - name: gpbackup_ddboost_plugin_tagged_src
+        outputs:
+          - name: ddboost_components
+        image_resource:
+          type: docker-image
+          source:
+            repository: pivotaldata/centos-gpdb-dev
+            tag: '6-gcc6.2-llvm3.7'
+        run:
+          path: bash
+          args:
+          - -c
+          - |
+            set -ex
+            pushd gpbackup_ddboost_plugin_tagged_src
+              # TODO: remove these steps once ddboost plugin is revved
+              curl -u${IVYREPO_USER}:${IVYREPO_PASSWD} -O "https://${IVYREPO_HOST}/gpdb-ext-release-local/third-party/ext/gpdb5_ext-3.3/targzs/rhel6_x86_64-gpdb5_ext-3.3.targz"
+              curl -u${IVYREPO_USER}:${IVYREPO_PASSWD} -O "https://${IVYREPO_HOST}/gpdb-ext-release-local/emc/DDBoostSDK/3.3.0.4-550644/targzs/DDBoostSDK-rhel5_x86_64-3.3.0.4-550644.targz"
+              tar -xf rhel6_x86_64-gpdb5_ext-3.3.targz
+              tar -xf DDBoostSDK-rhel5_x86_64-3.3.0.4-550644.targz
+              sudo cp rhel6_x86_64/include/yaml.h /usr/local/include/yaml.h
+              sudo cp rhel5_x86_64/include/* /usr/local/include/.
+              sudo cp rhel6_x86_64/lib/libyaml*so* /usr/lib64/.
+              sudo cp rhel5_x86_64/lib/libDDBoost.so /usr/lib64/.
+
+              make build
+              ddboost_plugin_version=`git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/'`
+            popd
+            echo ${ddboost_plugin_version} > ddboost_components/ddboost_plugin_version
+            cp gpbackup_ddboost_plugin_tagged_src/gpbackup_ddboost_plugin ddboost_components/
+  - task: tar-binaries
+    config:
+      platform: linux
+      inputs:
+        - name: go_components
+        - name: ddboost_components
+      outputs:
+        - name: github_release_components
+      image_resource:
+        type: docker-image
+        source:
+          repository: pivotaldata/centos-gpdb-dev
+          tag: '6-gcc6.2-llvm3.7'
+      run:
+        path: bash
+        args:
+        - -c
+        - |
+          set -ex
+          pushd github_release_components
+            # Create install script
+            printf "#!/bin/sh\nset -x\ntar -xzvf bin_gpbackup.tar.gz -C \$GPHOME" > install_gpdb_component
+            chmod +x install_gpdb_component
+
+            cp ../go_components/*_version .
+            mv ../go_components/gpbackup_version version
+            cp ../ddboost_components/*_version .
+
+            mkdir -p bin
+            cp ../go_components/gpbackup bin/
+            cp ../go_components/gpbackup_helper bin/
+            cp ../go_components/gprestore bin/
+            cp ../go_components/gpbackup_s3_plugin bin/
+            cp ../go_components/gpbackup_manager bin/
+            cp ../ddboost_components/gpbackup_ddboost_plugin bin/
+            # # Create test script
+            # cp ../gpbackup_version .
+            # cp ../gpbackup_version version
+            # cp ../s3_plugin_version .
+            # cp $GOPATH/src/github.com/greenplum-db/gpbackup/ci/scripts/smoke_test_component_gpbackup.sh smoke_test_gpdb_component
+            # # Assemble binaries
+            # mkdir -p bin
+            # cp $GOPATH/bin/gpbackup bin/
+            # cp $GOPATH/bin/gpbackup_helper bin/
+            # cp $GOPATH/bin/gprestore bin/
+            # cp $GOPATH/bin/gpbackup_s3_plugin bin/
+            # cp $GOPATH/bin/gpbackup_manager bin/
+
+            # need to end up with a folder bin with everything
+
+            # Test package
+            export PATH=$PATH:`pwd`/bin
+            # TODO reenable this
+            # ./smoke_test_gpdb_component
+
+            tar -czvf bin_gpbackup.tar.gz bin/
+
+            version=`cat version`
+            tar -czvf "gpbackup-${version}.tar.gz" bin_gpbackup.tar.gz install_gpdb_component gpbackup_version version s3_plugin_version
+          popd
+  - task: build_gppkg
+    file: gpbackup/ci/tasks/build-gppkg.yml
+    input_mapping:
+      gpdb_src: gpdb6_src
+      bin_gpdb: bin_gpdb_6x_stable_centos6
+    on_failure:
+      *slack_alert
+
+  - put: gppkgs
+    params:
+      file: gppkgs/gpbackup-gppkgs.tar.gz
+
+  - put: github_release_components
+    params:
+      file: github_release_components/gpbackup-*.tar.gz
+
+
 - name: build_dependencies
   plan:
   - aggregate:
@@ -393,7 +591,6 @@ jobs:
     - get: gpbackup_s3_plugin
       trigger: true
     - get: gpbackup
-      trigger: true
     - get: ccp_src
     - get: gpdb5_src
     - get: bin_gpdb_5x_stable_centos6
@@ -402,6 +599,11 @@ jobs:
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
+    # not used; it serves only as a trigger
+    - get: gppkgs
+      passed:
+       - build_binaries
+      trigger: true
   - put: terraform
     params:
       <<: *ccp_default_params
@@ -682,7 +884,6 @@ jobs:
       trigger: true
     - get: gpbackup
       tags: ["ddboost"]
-      trigger: true
     - get: ccp_src
       tags: ["ddboost"]
     - get: gpdb5_src
@@ -697,6 +898,12 @@ jobs:
       tags: ["ddboost"]
       passed:
        - build_dependencies
+    # not used; it serves only as a trigger
+    - get: gppkgs
+      tags: ["ddboost"]
+      passed:
+       - build_binaries
+      trigger: true
   - put: ddboost_terraform
     tags: ["ddboost"]
     params:
@@ -869,7 +1076,6 @@ jobs:
   plan:
   - aggregate:
     - get: gpbackup
-      trigger: true
     - get: bin_gpdb_5x_stable_centos6
     - get: ccp_src
     - get: gpdb5_src
@@ -877,7 +1083,12 @@ jobs:
       trigger: true
     - get: gpbackup-dependencies
       passed:
-       - build_dependencies
+      - build_dependencies
+    # not used; it serves only as a trigger
+    - get: gppkgs
+      passed:
+       - build_binaries
+      trigger: true
   - put: terraform
     params:
       <<: *ccp_default_params
@@ -908,7 +1119,6 @@ jobs:
   plan:
   - aggregate:
     - get: gpbackup
-      trigger: true
     - get: bin_gpdb_5x_stable_centos7
     - get: ccp_src
     - get: gpdb5_src
@@ -917,6 +1127,10 @@ jobs:
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
+    - get: gppkgs
+      trigger: true
+      passed:
+       - build_binaries
   - put: terraform_aws
     params:
       <<: *ccp_default_params_aws
@@ -957,7 +1171,6 @@ jobs:
     - get: centos6-image
     - get: centos7-image
     - get: gpbackup
-      trigger: true
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
@@ -967,6 +1180,11 @@ jobs:
     - get: nightly-trigger
       trigger: true
     - get: dummy_seclabel_linux_master
+    # not used; it serves only as a trigger
+    - get: gppkgs
+      passed:
+       - build_binaries
+      trigger: true
   - aggregate:
     - task: run-tests-locally-centos6
       image: centos6-image
@@ -993,7 +1211,6 @@ jobs:
   plan:
   - aggregate:
     - get: gpbackup
-      trigger: true
     - get: bin_gpdb_5x_stable_centos6
     - get: ccp_src
     - get: gpdb5_src
@@ -1002,6 +1219,10 @@ jobs:
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
+    - get: gppkgs
+      trigger: true
+      passed:
+       - build_binaries
   - put: terraform
     params:
       <<: *ccp_default_params
@@ -1031,7 +1252,6 @@ jobs:
   plan:
   - aggregate:
     - get: gpbackup
-      trigger: true
     - get: bin_gpdb_43_stable
     - get: ccp_src
     - get: gpdb5_src
@@ -1040,6 +1260,10 @@ jobs:
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
+    - get: gppkgs
+      trigger: true
+      passed:
+       - build_binaries
   - put: terraform
     params:
       <<: *ccp_default_params
@@ -1071,7 +1295,6 @@ jobs:
     - get: centos6-image
     - get: centos7-image
     - get: gpbackup
-      trigger: true
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
@@ -1081,6 +1304,10 @@ jobs:
     - get: nightly-trigger
       trigger: true
     - get: dummy_seclabel_linux_gpdb6
+    - get: gppkgs
+      trigger: true
+      passed:
+       - build_binaries
   - aggregate:
     - task: run-tests-locally-centos6
       image: centos6-image
@@ -1107,7 +1334,6 @@ jobs:
   plan:
   - aggregate:
     - get: gpbackup
-      trigger: true
     - get: bin_gpdb_5x_stable_centos6
     - get: ccp_src
     - get: gpdb5_src
@@ -1116,6 +1342,10 @@ jobs:
     - get: gpbackup-dependencies
       passed:
        - build_dependencies
+    - get: gppkgs
+      trigger: true
+      passed:
+       - build_binaries
   - put: terraform
     params:
       <<: *ccp_default_params
